# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36b86d38a470f36de03f8926bc7bd8ef3c43ef1646e706b05cafe59f57bb7d95ac7c08b034292a8a5042ebefca2bffd5cef86e59c5ec05e0262e829211a2a6af

test:
  secret_key_base: e005b0469229b26b8eba471b4b9c0268e08b5b116b4a26cf6f64a3d67d1ac06f8da08d4e5bf1a112acd5d7d1f15649ea25263f22f1650058c3c324a36e30b0ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
